// This file is part of midnightntwrk/example-counter.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the Midnight bulletin board example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

// Wallet seed: 8dd96c613b92a1ced03ac5e71a039d4447cfe84928864fc38260b28cd30378c2

import { createInterface, type Interface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { WebSocket } from "ws";
// import { webcrypto } from 'crypto';
import {
  type ContractProviders,
  ContractAPI,
  utils,
  type ContractDerivedState,
  type DeployedContractContract,
  type PrivateStateId,
  contractPrivateStateKey,
} from "contract-api";
import {
  ledger,
  pureCircuits,
  type Ledger,
} from "contract-primitives";
import {
  type BalancedTransaction,
  createBalancedTx,
  type MidnightProvider,
  PublicDataProvider,
  type UnbalancedTransaction,
  type WalletProvider,
} from "@midnight-ntwrk/midnight-js-types";
import { type Wallet } from "@midnight-ntwrk/wallet-api";
import * as Rx from "rxjs";
import {
  type CoinInfo,
  nativeToken,
  Transaction,
  type TransactionId,
} from "@midnight-ntwrk/ledger";
import { Transaction as ZswapTransaction } from "@midnight-ntwrk/zswap";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import { type Resource, WalletBuilder } from "@midnight-ntwrk/wallet";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { type Logger } from "pino";
import { type Config, StandaloneConfig } from "./config.js";
import type {
  StartedDockerComposeEnvironment,
  DockerComposeEnvironment,
} from "testcontainers";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { QualifiedCoinInfo, type ContractAddress } from "@midnight-ntwrk/compact-runtime";
import {
  toHex,
  assertIsContractAddress,
  fromHex,
} from "@midnight-ntwrk/midnight-js-utils";
import {
  getLedgerNetworkId,
  getZswapNetworkId,
} from "@midnight-ntwrk/midnight-js-network-id";

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getBBoardLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific bulletin board contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the bulletin board contract.
 */

export const getContractLedgerState = async (
  providers: ContractProviders,
  contractAddress: ContractAddress
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState =
    await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};
// providers.publicDataProvider
//   .queryContractState(contractAddress)
//   .then((contractState) => (contractState != null ? ledger(contractState.data) : null));

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
    You can do one of the following:
      1. Deploy a new tokenization contract
      2. Join an existing tokenization contract
      3. Exit
    Which would you like to do? `;

const deployOrJoin = async (
  providers: ContractProviders,
  rli: Interface,
  logger: Logger,
  contractInstance?: string
): Promise<ContractAPI | null> => {
  let api: ContractAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case "1":
        api = await ContractAPI.deploy(providers, logger);
        logger.info(
          `Deployed contract at address: ${api.deployedContractAddress}`
        );
        return api;
      case "2":
        api = await ContractAPI.join(
          providers,
          contractInstance ??
            (await rli.question("What is the contract address (in hex)? ")),
          logger
        );
        logger.info(
          `Joined contract at address: ${api.deployedContractAddress}`
        );
        return api;
      case "3":
        logger.info("Exiting...");
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the bulletin board.
 */

const displayLedgerState = async (
  providers: ContractProviders,
  deployedContractContract: DeployedContractContract,
  logger: Logger
): Promise<void> => {
  const contractAddress =
    deployedContractContract.deployTxData.public.contractAddress;
  const ledgerState = await getContractLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no contract contract deployed at ${contractAddress}`);
  } else {
    logger.info(`Current ledger state:`);
    console.dir(ledgerState, { depth: null });
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */

const displayPrivateState = async (
  providers: ContractProviders,
  logger: Logger
): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(
    contractPrivateStateKey
  );
  if (privateState === null) {
    logger.info(`There is no existing bulletin board private state`);
  } else {
    logger.info(`Current secret key is: ${toHex(privateState.secret_key)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the poster key with the private secret key to
 * determine if the current user is the poster of the current message.
 */

const displayDerivedState = async (
  providers: ContractProviders,
  ledgerState: ContractDerivedState | undefined,
  logger: Logger,
  contractApi: ContractAPI
) => {
  if (ledgerState === undefined) {
    logger.info(`No state currently available`);
  } else {
    logger.info(`Current derived state:`);
    console.dir(ledgerState, { depth: null });
  }
  const state = await providers.publicDataProvider.queryZSwapAndContractState(
    contractApi.deployedContractAddress
  );
  console.dir(state?.[0].toString(), { depth: null });
};
/* **********************************************************************
 * mainLoop: the main interactive menu of the bulletin board CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Mint shares
  2. Display the current ledger state (known by everyone)
  3. Display the current private state (known only to this DApp instance)
  4. Display the derived state (known by everyone)
  5. Exit
  6. Show Wallet balance
  7. send nft
  8 . Sell Shares
  9 . Buy Share
Which would you like to do? `;

const mainLoop = async (
  providers: ContractProviders,
  rli: Interface,
  logger: Logger,
  wallet: Wallet,
  contractInstance?: string
): Promise<void> => {
  const contractApi = await deployOrJoin(
    providers,
    rli,
    logger,
    contractInstance
  );

  const testnet_addr =
    "mn_shield-addr_test1chhe5tpv9ugmgg2kl523qrp965gkafqm3cc8d9tvtkrw0jced93sxqx7npgcz9xhna2futff2hq8d8afujw8qzenmxqtpkwgxn93yheg7v8xh6kr";
  if (contractApi === null) {
    return;
  }
  let currentState: ContractDerivedState | undefined;
  const stateObserver = {
    next: (state: ContractDerivedState) => (currentState = state),
  };
  const subscription = contractApi.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      switch (choice) {
        case "1": {
          try {
            await contractApi.mintShare();
          } catch (e) {
            logger.error(
              `Failed to mint shares: ${e instanceof Error ? e.message : e}`
            );
          }
          break;
        }
        case "2":
          await displayLedgerState(
            providers,
            contractApi.deployedContract,
            logger
          );
          break;
        case "3":
          await displayPrivateState(providers, logger);
          break;
        case "4":
          await displayDerivedState(
            providers,
            currentState,
            logger,
            contractApi
          );
          break;
        case "5":
          logger.info("Exiting...");
          return;
        case "6":
          await displayComprehensiveWalletState(wallet, logger);
          break;
        case "7":
          const state = await Rx.firstValueFrom(wallet.state());

          const tokenType = Object.entries(state.balances)[1][0];
          const recipe = await wallet.transferTransaction([
            {
              amount: Object.entries(state.balances)[1][1],
              type: tokenType,
              receiverAddress: testnet_addr,
            },
          ]);

          let zswapTx = await wallet.proveTransaction(recipe);
          await wallet.submitTransaction(zswapTx);
          break;
        case "8": {
          const state = await Rx.firstValueFrom(wallet.state());
          console.log(state.availableCoins)
          const {type, nonce, value, mt_index}: QualifiedCoinInfo = state.availableCoins[1];

          await contractApi.sellShares(type, nonce, value);
          break;
        }
        case "9":
          // owner should be read from contract state
          const secretKeyAgus =
            "8c358fc3df48a8159758a8a3bf24b4133c2276fc15aeb4dd69b6af4867e3ef03";
          const salt =
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
          const nullOwner = pureCircuits.nullify(
            fromHex(secretKeyAgus),
            fromHex(salt)
          );
          await contractApi.buyShare(nullOwner);
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* **********************************************************************
 * createWalletAndMidnightProvider: returns an object that
 * satifies both the WalletProvider and MidnightProvider
 * interfaces, both implemented in terms of the given wallet.
 */

const createWalletAndMidnightProvider = async (
  wallet: Wallet
): Promise<WalletProvider & MidnightProvider> => {
  const state = await Rx.firstValueFrom(wallet.state());
  return {
    coinPublicKey: state.coinPublicKey,
    encryptionPublicKey: state.encryptionPublicKey,
    balanceTx(
      tx: UnbalancedTransaction,
      newCoins: CoinInfo[]
    ): Promise<BalancedTransaction> {
      return wallet
        .balanceTransaction(
          ZswapTransaction.deserialize(
            tx.serialize(getLedgerNetworkId()),
            getZswapNetworkId()
          ),
          newCoins
        )
        .then((tx) => wallet.proveTransaction(tx))
        .then((zswapTx) =>
          Transaction.deserialize(
            zswapTx.serialize(getZswapNetworkId()),
            getLedgerNetworkId()
          )
        )
        .then(createBalancedTx);
    },
    submitTx(tx: BalancedTransaction): Promise<TransactionId> {
      return wallet.submitTransaction(tx);
    },
  };
};

/* **********************************************************************
 * waitForFunds: wait for tokens to appear in a wallet.
 *
 * This is an interesting example of watching the stream of states
 * coming from the pub-sub indexer.  It watches both
 *  1. how close the state is to present reality and
 *  2. the balance held by the wallet.
 */

const waitForFunds = (wallet: Wallet, logger: Logger) =>
  Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.tap((state) => {
        const scanned = state.syncProgress?.synced ?? 0n;
        const behind =
          state.syncProgress?.lag.applyGap.toString() ?? "unknown number";
        logger.info(`Wallet processed ${scanned} indices, remaining ${behind}`);
      }),
      Rx.filter((state) => {
        // Let's allow progress only if wallet is close enough
        const synced =
          typeof state.syncProgress?.synced === "bigint"
            ? state.syncProgress.synced
            : 0n;
        const total =
          typeof state.syncProgress?.lag?.applyGap === "bigint"
            ? state.syncProgress.lag.applyGap
            : 1_000n;
        return total - synced < 100n;
      }),
      Rx.map((s) => s.balances[nativeToken()] ?? 0n),
      Rx.filter((balance) => balance > 0n)
    )
  );

/* **********************************************************************
 * buildWalletAndWaitForFunds: the main function that creates a wallet
 * and waits for tokens to appear in it.  The various "buildWallet"
 * functions all arrive here after collecting information for the
 * arguments.
 */

const buildWalletAndWaitForFunds = async (
  { indexer, indexerWS, node, proofServer }: Config,
  logger: Logger,
  seed: string
): Promise<Wallet & Resource> => {
  const wallet = await WalletBuilder.buildFromSeed(
    indexer,
    indexerWS,
    proofServer,
    node,
    seed,
    getZswapNetworkId(),
    "warn"
  );
  wallet.start();
  const state = await Rx.firstValueFrom(wallet.state());
  logger.info(`Your wallet seed is: ${seed}`);
  logger.info(`Your wallet address is: ${state.address}`);
  let balance = state.balances[nativeToken()];
  if (balance === undefined || balance === 0n) {
    logger.info(`Your wallet balance is: 0`);
    logger.info(`Waiting to receive tokens...`);
    balance = await waitForFunds(wallet, logger);
  }
  logger.info(`Your wallet balance is: ${balance}`);
  return wallet;
};

// Generate a random see and create the wallet with that.
const buildFreshWallet = async (
  config: Config,
  logger: Logger
): Promise<Wallet & Resource> =>
  await buildWalletAndWaitForFunds(
    config,
    logger,
    toHex(utils.randomBytes(32))
  );

// Prompt for a seed and create the wallet with that.
const buildWalletFromSeed = async (
  config: Config,
  rli: Interface,
  logger: Logger,
  seedd?: string
): Promise<Wallet & Resource> => {
  const seed = await rli.question("Enter your wallet seed: ");
  return await buildWalletAndWaitForFunds(config, logger, seedd ?? seed);
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED =
  "0000000000000000000000000000000000000000000000000000000000000001";

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (
  config: Config,
  rli: Interface,
  logger: Logger,
  seed?: string
): Promise<(Wallet & Resource) | null> => {
  if (config instanceof StandaloneConfig) {
    return await buildWalletAndWaitForFunds(
      config,
      logger,
      GENESIS_MINT_WALLET_SEED
    );
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case "1":
        return await buildFreshWallet(config, logger);
      case "2":
        return await buildWalletFromSeed(config, rli, logger, seed);
      case "3":
        logger.info("Exiting...");
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

const mapContainerPort = (
  env: StartedDockerComposeEnvironment,
  url: string,
  containerName: string
) => {
  const mappedUrl = new URL(url);
  const container = env.getContainer(containerName);

  mappedUrl.port = String(container.getFirstMappedPort());

  return mappedUrl.toString().replace(/\/+$/, "");
};

/* **********************************************************************
 * run: the main entry point that starts the whole bulletin board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (
  config: Config,
  logger: Logger,
  dockerEnv?: DockerComposeEnvironment
): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  let env;
  if (dockerEnv !== undefined) {
    env = await dockerEnv.up();

    if (config instanceof StandaloneConfig) {
      config.indexer = mapContainerPort(env, config.indexer, "example-indexer");
      config.indexerWS = mapContainerPort(
        env,
        config.indexerWS,
        "example-indexer"
      );
      config.node = mapContainerPort(env, config.node, "example-node");
      config.proofServer = mapContainerPort(
        env,
        config.proofServer,
        "example-proof-server"
      );
    }
  }
  const wallet = await buildWallet(config, rli, logger);
  try {
    if (wallet !== null) {
      const walletAndMidnightProvider =
        await createWalletAndMidnightProvider(wallet);
      const providers = {
        privateStateProvider: levelPrivateStateProvider<PrivateStateId>({
          privateStateStoreName: config.privateStateStoreName,
        }),
        publicDataProvider: indexerPublicDataProvider(
          config.indexer,
          config.indexerWS
        ),
        zkConfigProvider: new NodeZkConfigProvider<"mintShare">(
          config.zkConfigPath
        ),
        proofProvider: httpClientProofProvider(config.proofServer),
        walletProvider: walletAndMidnightProvider,
        midnightProvider: walletAndMidnightProvider,
      };
      await mainLoop(providers, rli, logger, wallet);
    }
  } catch (e) {
    logError(logger, e);
    logger.info("Exiting...");
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        if (wallet !== null) {
          await wallet.close();
        }
      } catch (e) {
        logError(logger, e);
      } finally {
        try {
          if (env !== undefined) {
            await env.down();
            logger.info("Goodbye");
            process.exit(0);
          }
        } catch (e) {
          logError(logger, e);
        }
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}

// Function to display comprehensive wallet state including all token types
async function displayComprehensiveWalletState(
  wallet: Wallet,
  logger: Logger
): Promise<void> {
  const state = await Rx.firstValueFrom(wallet.state());

  logger.info("=== WALLET STATE ===");
  logger.info(`Address: ${state.address}`);
  logger.info(
    `Sync Status: ${state.syncProgress?.synced ? "SYNCED" : "SYNCING"}`
  );

  if (state.syncProgress) {
    logger.info(`Apply Gap: ${state.syncProgress.lag.applyGap}`);
    logger.info(`Source Gap: ${state.syncProgress.lag.sourceGap}`);
  }

  logger.info("=== TOKEN BALANCES ===");
  Object.entries(state.balances).forEach(([tokenType, balance]) => {
    if (tokenType === nativeToken()) {
      logger.info(`Native Token (tDUST): ${balance}`);
    } else {
      logger.info(`Token ${tokenType}: ${balance}`);
    }
  });

  logger.info(`Transaction History Count: ${state.transactionHistory.length}`);
  logger.info("===================");
}
